# Form implementation generated from reading ui file 'c:\Users\Alireza\Git_Projects\AP_Project\login.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(443, 228)
        self.layoutWidget = QtWidgets.QWidget(Login)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 383, 161))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.usernamelbl = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.usernamelbl.setFont(font)
        self.usernamelbl.setObjectName("usernamelbl")
        self.horizontalLayout.addWidget(self.usernamelbl)
        self.usernameled = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.usernameled.setFont(font)
        self.usernameled.setObjectName("usernameled")
        self.horizontalLayout.addWidget(self.usernameled)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.passwordlbl = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.passwordlbl.setFont(font)
        self.passwordlbl.setObjectName("passwordlbl")
        self.horizontalLayout_2.addWidget(self.passwordlbl)
        self.passwordled = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.passwordled.setFont(font)
        self.passwordled.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordled.setObjectName("passwordled")
        self.horizontalLayout_2.addWidget(self.passwordled)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.donthaveacclbl = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.donthaveacclbl.setFont(font)
        self.donthaveacclbl.setObjectName("donthaveacclbl")
        self.horizontalLayout_3.addWidget(self.donthaveacclbl)
        self.signupbtn = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        self.signupbtn.setFont(font)
        self.signupbtn.setObjectName("signupbtn")
        self.horizontalLayout_3.addWidget(self.signupbtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.loginStat = QtWidgets.QLabel(self.layoutWidget)
        self.loginStat.setText("")
        self.loginStat.setObjectName("loginStat")
        self.verticalLayout.addWidget(self.loginStat)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login Page"))
        self.usernamelbl.setText(_translate("Login", "Username"))
        self.passwordlbl.setText(_translate("Login", "Password"))
        self.donthaveacclbl.setText(_translate("Login", "Don\'t have an account?"))
        self.signupbtn.setText(_translate("Login", "Sign up"))
